service:
  name: endless-fun-5

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  dotenv:
    path: ./dotenv/.env

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: 'ApiGatewayRestApi'

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${env:AWS_CONFIG_PROFILE}
  region: ${env:AWS_CONFIG_REGION}

functions:
  recognize:
    handler: src/index.recognize
    events:
      - http:
          method: post
          path: recognize
          cors: true
