service:
  name: endless-fun-6

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  dotenv:
    path: ./dotenv/.env

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${env:AWS_CONFIG_PROFILE}
  region: ${env:AWS_CONFIG_REGION}

functions:
  recognize:
    handler: src/index.recognize
    events:
      - http:
          method: post
          path: /story-item/{storyItemId}/rekognize
          cors: true
          request:
            parameters:
              paths:
                storyItemId: true
  game:
    handler: src/index.game
    events:
      - http:
          method: get
          path: /game/{gameId}
          cors: true
          request:
            parameters:
              paths:
                gameId: true
  results:
    handler: src/index.results
    events:
      - http:
          method: get
          path: /game/{gameId}/results
          cors: true
          request:
            parameters:
              paths:
                gameId: true
