service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  dotenv:
    path: ./dotenv/.env

provider:
  name: aws
  runtime: nodejs8.10
  profile: qestdev-rast
  region: eu-central-1

functions:
  hello:
    handler: src/index.hello
    events:
      - http:
          method: get
          path: hello
  info:
    handler: src/index.info
    events:
      - http:
          method: get
          path: info
