service:
  name: aws-nodejs-typescript

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin
custom:
  dotenv:
    path: ./dotenv/.env

provider:
  name: aws
  runtime: nodejs8.10
  profile: ${env:AWS_CONFIG_PROFILE}
  region: ${env:AWS_CONFIG_REGION}
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'SNS:Publish'
      Resource: 'arn:aws:sns:${env:AWS_CONFIG_REGION}:${env:AWS_CONFIG_ACCOUNT_ID}:${env:SNS_TOPIC_NAME}'

functions:
  hello:
    handler: src/index.hello
    events:
      - http:
          method: get
          path: hello
  info:
    handler: src/index.info
    events:
      - http:
          method: get
          path: info
  snsLamdbaTriggered:
    handler: src/index.snsLamdbaTriggered
    events:
      - sns: ${env:SNS_TOPIC_NAME}
